# Generated by Django 4.1.3 on 2022-12-11 02:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion', verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion', verbose_name='modificado')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'productos_Productos',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion', verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion', verbose_name='modificado')),
                ('imagen', models.FileField(upload_to='producto/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'PNG'])])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.productos')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
                'db_table': 'productos_Imagen',
            },
        ),
    ]
