# Generated by Django 4.1.3 on 2022-12-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_productos_precio'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionCategoriasProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion', verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion', verbose_name='modificado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categorias')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.productos')),
            ],
            options={
                'verbose_name_plural': 'Relacion Categorias Productos',
                'db_table': 'categorias_RelacionCategoriasProductos',
            },
        ),
    ]
